config/routes.rb
Rails.application.routes.draw do
  root "spend_forecasts#index"
  resources :spend_forecasts, except: [:destroy, :create] do
    get :download_budget_csv, on: :member
  end

  resources :users, only: [] do
    get :download_budget_template_csv, on: :member
  end

  post :process_budget, to: 'budgets#process_budget'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget
  attr_reader :processed_budget, :rows_lost, :start_date, :end_date, :channel_daily_spend_limit, :rows_lost, :user

  def initialize(budget_contents:, start_date:, end_date:, channel_daily_spend_limit:, user:)
    @budget_contents = CSV.parse(budget_contents, headers: true)
    @start_date = start_date
    @end_date = end_date
    @channel_daily_spend_limit = channel_daily_spend_limit.to_i
    @user = user
  end

  def spend_forecast_from_budget
    user.spend_forecasts.new(start_date:, end_date:, budget: processed_budget, channel_daily_spend_limit:, rows_lost:)
  end

  def process_budget
    filtered_budget = @budget_contents.select do |row|
      date = Date.parse(row['date'])
      total_spending = row.to_h.values[1..-1].map(&:to_i).sum
      date >= start_date && date <= end_date && total_spending < channel_daily_spend_limit
    end

    filtered_budget_array = filtered_budget.map(&:fields)
    filtered_budget_array.unshift(@budget_contents.headers)
    rows_lost = (@budget_contents.to_a - filtered_budget_array)
    rows_lost.unshift(@budget_contents.headers) if rows_lost.any?

    @processed_budget = filtered_budget_array
    @rows_lost = rows_lost
  end
end

app/models/spend_forecast.rb
class SpendForecast < ApplicationRecord
  STATUSES = %w[draft in_progress completed].freeze

  validates :name, presence: true, unless: :draft?
  validates :start_date, presence: true, unless: :draft?
  validates :end_date, presence: true, unless: :draft?
  validates :budget, presence: true, unless: :draft?
  validates :status, presence: true, inclusion: { in: STATUSES }
  validate :end_date_after_start_date

  attr_accessor :budget_file, :rows_lost

  enum status: STATUSES.index_by(&:to_sym)

  belongs_to :user

  private

  def end_date_after_start_date
    if end_date.present? && start_date.present? && end_date < start_date
      errors.add(:end_date, "must be after or equal to start date")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :spend_forecasts
end

app/controllers/application_controller.rb
require 'csv'
class ApplicationController < ActionController::Base

  def current_user
    @current_user ||= User.first || User.create(channels: %w[facebook radio	billboards])
  end
  helper_method :current_user
end

app/controllers/budgets_controller.rb
require 'csv'

class BudgetsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def process_budget
    user = User.find(params[:user_id])
    budget.process_budget

    Turbo::StreamsChannel.broadcast_replace_to(
      user,
      target: "spend_forecast",
      partial: "spend_forecasts/form",
      locals: { user:, spend_forecast: budget.spend_forecast_from_budget}
    )
  end

  private

  def user
    @user ||= User.find(params[:user_id])
  end

  def budget
    @budget ||= Budget.new(
      budget_contents: params[:budget_file_contents],
      start_date: Date.parse(params[:start_date]),
      end_date: Date.parse(params[:end_date]),
      channel_daily_spend_limit: params[:channel_daily_spend_limit].to_i,
      user:
    )
  end
end

app/controllers/spend_forecasts_controller.rb
class SpendForecastsController < ApplicationController
  before_action :set_spend_forecast, only: [:download_budget_csv, :show]

  def index
    @spend_forecasts = SpendForecast.all
  end

  def new
    @spend_forecast = current_user.spend_forecasts.find_by(status: :draft) || current_user.spend_forecasts.create
  end

  def edit
    @spend_forecast = current_user.spend_forecasts.draft.find(params[:id])
  end

  def update
    @spend_forecast = current_user.spend_forecasts.draft.find(params[:id])
    @spend_forecast.update(spend_forecast_params)

    if @spend_forecast.update(status: :in_progress)
      redirect_to spend_forecast_path(@spend_forecast)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if spend_forecast.update(spend_forecast_params)
      redirect_to spend_forecast_path(spend_forecast)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def create
    if spend_forecast.update(spend_forecast_params)
      redirect_to spend_forecast_path(spend_forecast)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show;end

  def download_budget_csv
    csv_data = CSV.generate(headers: true) do |csv|
      @spend_forecast.budget.each do |row|
        csv << row
      end
    end

    send_data csv_data, filename: "#{@spend_forecast.name}.csv", type: 'text/csv'
  end

  private

  def set_spend_forecast
    @spend_forecast = current_user.spend_forecasts.find(params[:id])
  end

  def spend_forecast_params
    params.require(:spend_forecast).permit(:name, :start_date, :end_date, :channel_daily_spend_limit, :budget)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def download_budget_template_csv
    headers = ['date'] + current_user.channels

    csv_data = CSV.generate(headers: true) do |csv|
      csv << headers
      csv << [Date.today]
    end

    send_data csv_data, filename: "budget_template.csv", type: 'text/csv'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100">
    <nav class="bg-white shadow-md">
      <div class="container mx-auto p-4 flex justify-start items-center">
        <div class="text-lg font-semibold mr-8">
          MarketingApp
        </div>
        <div class="flex space-x-4">
          <%= link_to "Index", spend_forecasts_path, class: "text-gray-700 hover:text-gray-900 px-3 py-2 rounded-md text-s font-medium" %>
        </div>
      </div>
    </nav>

    <div class="container mx-auto p-6">
      <%= yield %>
    </div>
  </body>
</html>

app/views/spend_forecasts/_form.html.erb
<%= form_for spend_forecast, id: 'spend_forecast', html: { data: { controller: "budget-file", budget_file_target: "form", budget_file_user_id: user.id } } do |f| %>
    <% if spend_forecast.errors.any? %>
        <div class="mb-4 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
            <strong class="font-bold">There were some errors with your submission:</strong>
            <ul class="list-disc pl-5 mt-2">
                <% @spend_forecast.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="mb-4">
        <%= f.label :name, 'Name:', class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>
    
    <div class="flex space-x-4 mb-4">
        <div class="w-1/2">
        <%= f.label :start_date, 'Start Date:', class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.date_field :start_date, id: :start_date, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>
        <div class="w-1/2">
        <%= f.label :end_date, 'End Date:', class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.date_field :end_date, id: :end_date, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        </div>
    </div>

    <div class="mb-4">
        <%= f.label :channel_daily_spend_limit, 'Daily spend limit for a channel:', class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.text_field :channel_daily_spend_limit, id: :channel_daily_spend_limit, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-4">
        <%= f.label :budget_file, 'Budget CSV:', class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.file_field :budget_file, accept: 'text/csv', data: { target: "budget-file.input" }, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <%= f.hidden_field :budget, value: f.object.budget.to_json %>

    <% if f.object.budget.present? %>
        <h1> Rows present in spend forecast: </h1>
        <div class="overflow-x-auto">
            <table class="min-w-full bg-white shadow-md rounded-lg overflow-hidden">
            <thead>
                <tr class="bg-gray-800 text-white">
                <% f.object.budget.first.each do |header| %>
                    <th class="py-2 px-4 text-left"><%= header.capitalize %></th>
                <% end %>
                </tr>
            </thead>
            <tbody>
                <% f.object.budget.drop(1).each do |entry| %>
                <tr class="border-b border-gray-200">
                    <% entry.each do |value| %>
                    <td class="py-2 px-4"><%= value %></td>
                    <% end %>
                </tr>
                <% end %>
            </tbody>
            </table>
        </div>
    <% end %>

    <% if f.object.rows_lost.present? %>
        <h1> Rows missing from spend forecast: </h1>
        <div class="overflow-x-auto">
            <table class="min-w-full bg-white shadow-md rounded-lg overflow-hidden">
            <thead>
                <tr class="bg-gray-800 text-white">
                <% f.object.rows_lost.first.to_a.each do |header| %>
                    <th class="py-2 px-4 text-left"><%= header.capitalize %></th>
                <% end %>
                </tr>
            </thead>
            <tbody>
                <% f.object.rows_lost.drop(1).each do |entry| %>
                <tr class="border-b border-gray-200">
                    <% entry.each do |value| %>
                    <td class="py-2 px-4"><%= value %></td>
                    <% end %>
                </tr>
                <% end %>
            </tbody>
            </table>
        </div>
    <% end %>

    <div class="flex items-center justify-end mt-4">
        <%= f.submit 'Create Spend Forecast', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        <%= link_to 'Download Budget CSV template', download_budget_template_csv_user_path(spend_forecast.user, format: :csv), class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline ml-4" %>
    </div>
<% end %>

app/views/spend_forecasts/edit.html.erb
<div class="container mx-auto p-6">
    <h1 class="text-3xl font-bold mb-6">Edit Spend Forecast</h1>
    <div class="bg-white p-6 rounded-lg shadow-md">
        <%= render 'form', spend_forecast: @spend_forecast, user: current_user %>
    </div>
</div>

app/views/spend_forecasts/index.html.erb
<div class="container mx-auto p-6">
  <h1 class="text-3xl font-bold mb-6">Spend Forecasts</h1>
  <div class="bg-white p-6 rounded-lg shadow-md overflow-x-auto">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Name
          </th>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Start Date
          </th>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            End Date
          </th>
          <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Status
          </th>
        </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
        <% @spend_forecasts.each do |spend_forecast| %>
          <tr>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
              <%= link_to spend_forecast.name, spend_forecast_path(spend_forecast), class: "text-blue-500 hover:text-blue-700" %>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
              <%= spend_forecast.start_date %>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
              <%= spend_forecast.end_date %>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
              <%= spend_forecast.status %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="mt-4 flex justify-end">
      <%= link_to "New", new_spend_forecast_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  </div>
</div>

app/views/spend_forecasts/new.html.erb
<div class="container mx-auto p-6">
    <h1 class="text-3xl font-bold mb-6">Create New Spend Forecast</h1>
    <div class="bg-white p-6 rounded-lg shadow-md">
        <div id="spend_forecast">
            <%= render 'form', spend_forecast: @spend_forecast, user: current_user %>
            <%= turbo_stream_from current_user %>
        </div>
    </div>
</div>

app/views/spend_forecasts/show.html.erb
<div class="container mx-auto p-6">
    <div class="mb-6">
        <h1 class="text-4xl font-bold mb-2">Spend Forecast "<%= @spend_forecast.name %>" </h1>
        <p class="text-lg text-gray-500">From <%= @spend_forecast.start_date %> to <%= @spend_forecast.end_date %></p>
    </div>
    <% if @spend_forecast.budget %>
        <div class="overflow-x-auto">
            <table class="min-w-full bg-white shadow-md rounded-lg overflow-hidden">
                <thead>
                    <tr class="bg-gray-800 text-white">
                    <% @spend_forecast.budget.first.each do |header| %>
                        <th class="py-2 px-4 text-left"><%= header.capitalize %></th>
                    <% end %>
                    </tr>
                </thead>
                <tbody>
                    <% @spend_forecast.budget.drop(1).each do |entry| %>
                    <tr class="border-b border-gray-200">
                        <% entry.each do |value| %>
                        <td class="py-2 px-4"><%= value %></td>
                        <% end %>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    <% end %>
    <div class="flex items-center justify-end mt-4">
        <% if @spend_forecast.budget.present? %>
            <%= link_to 'Download Budget CSV', download_budget_csv_spend_forecast_path(@spend_forecast, format: :csv), class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        <% end %>
        <% if @spend_forecast.draft? %>
            <%= link_to 'Edit', edit_spend_forecast_path(@spend_forecast), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline ml-4" %>
        <% end %>
    </div>
</div>